name: CI for pull request, notify test regression

on:
  pull_request:
    branches: ["dev","main"]
    types: [opened, synchronize, reopened]


jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check.outputs.skip }}


    steps:
      - name : checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
 
      - id: check
        run: |
          LAST_COMMIT_MSG=$(git log -1 --pretty=%B)

          if echo "$LAST_COMMIT_MSG" | grep -q "Ruff formatter"; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi
          
  job_format:
    name : ruff format
    needs : check
    if: needs.check.outputs.skip != 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          persist-credentials: false
          
      - name: Configuration
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          
      - name: Cache installation
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip- 

      - name: Installation package with editable mode
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Format
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_CI }}
        run: |
          ruff check --select I --fix src_lib src
          ruff format --config quality/ruff.toml src_lib src
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name "Ruff formatter"
            git config --global user.email "formatter@ruff.org"
            git add src_lib src
            git commit -m "Ruff format code and import"
            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
            git push
          else
            echo "No format."
          fi

  job_pytest:
    name : pytest
    needs: [check, job_format]
    if: needs.check.outputs.skip != 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
        
      - name: process
        run: |
          echo "Process pytest"
