name: CI for pull request, notify test regression

on:
  push:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Configuration
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          
      - name: Cache installation
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip- 

      - name: Installation package with editable mode
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Format
        env:
          GITHUB_TOKEN: ${{ secrets.token-classic }}
        run: |
          ruff check --select I --fix src_lib
          ruff format --config quality/ruff.toml src_lib
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name "GitHub CI"
            git config --global user.email "github.ci@example.com"
            git add src_lib
            git commit -m "GitHub CI format code"
            git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/${{ github.repository }}
            git push
          else
            echo "No format."
          fi

